### ISSUE TITLE
iBeacon UUID not recognized

### ISSUE THREAD

**Issue by mihsu81** [rpatel3001/BleDistance#2]
Hi @rpatel3001,

In whichever format I'm adding the iBeacon UUID, it is not recognized.
The iBeacon UUID from the HA app is: A099B5978F46-4A26-9109-DB0F-AB08D87A-100-1
Based on https://community.home-assistant.io/t/esphome-component-for-espresense-like-room-tracking/386678/27 it should be modified to: 7AD808AB0FDB-0991-264A-468F-97B599A0.
But all I'm getting is:
```
[17:45:52][V][sensor:076]: 'BETHAYN-ONEPLUS-8-BLE Distance': Received new state nan
[17:45:52][D][sensor:127]: 'BETHAYN-ONEPLUS-8-BLE Distance': Sending state nan m with 1 decimals of accuracy
```
Any suggestions?

**Comment by rpatel3001** [comment]
https://github.com/rpatel3001/BleDistance#important-note

Don't flip the UUID.

**Comment by mihsu81** [comment]
I've tried already with:
```        addTracker("BETHAYN-ONEPLUS-8-BLE-GATEWAY06-1", "A099B597-8F46-4A26-9109-DB0FAB08D87A-100-1"),```
and
```        addTracker("BETHAYN-ONEPLUS-8-BLE-GATEWAY06-1", "A099B597-8F46-4A26-9109-DB0FAB08D87A"),```
but i'm still not getting the distance.

**Comment by mihsu81** [comment]
> The iBeacon UUID from the HA app is: A099B5978F46-4A26-9109-DB0F-AB08D87A-100-1

The UUID is actually: A099B597-8F46-4A26-9109-DB0FAB08D87A-100-1

**Comment by rpatel3001** [comment]
Definitely leave off the major/minor (100-1). Are you certain the beacon is transmitting? Check with a BLE scanner on another phone or by following the esphome instructions for scanning: https://esphome.io/components/binary_sensor/ble_presence.html#esp32-ble-tracker-setting-up-devices

**Comment by mihsu81** [comment]
And the config of the device is:
```yaml
external_components:
  - source: github://myhomeiot/esphome-components
  - source: github://dentra/esphome-components
  - source: github://ayufan/esphome-components

substitutions:
  devicename: ble_gateway06
  friendly_name: BLE-GATEWAY06
  gateway_id: ble_gateway06

esphome:
  name: ble-gateway06
  includes:
    - custom_components/lib/OneEuro.h
    - custom_components/ble_dist.h
  on_boot:
    then:
      lambda: |-
        addTracker("BETHAYN-ONEPLUS-8-BLE-GATEWAY06-1", "A099B597-8F46-4A26-9109-DB0FAB08D87A"),
        addTracker("KAMY-HUAWEI-P30-BLE-GATEWAY06-1", "D5448F45-8403-4770-844D-DAB4E6873E51");

esp32:
  board: mhetesp32minikit
  framework:
    type: arduino

# Enable logging
logger:
  level: VERBOSE

# Enable Home Assistant API
api:
  reboot_timeout: 1h
  encryption:
    key: !secret api_encryption_key

ota:
  password: !secret ota_password

web_server:
  port: 80
  auth:
    username: !secret username
    password: !secret password
  include_internal: true

time:
  - platform: homeassistant
    id: homeassistant_time

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${devicename} Fallback"
    password: !secret esphome_fallback_password

captive_portal:

esp32_ble_tracker:
  scan_parameters:
    duration: 60s
    active: false

binary_sensor:
  - platform: ble_presence
    ibeacon_uuid: a099b597-8f46-4a26-9109-db0fab08d87a
    name: BETHAYN-ONEPLUS-8-BLE-GATEWAY06
  - platform: ble_presence
    ibeacon_uuid: d5448f45-8403-4770-844d-dab4e6873e51
    name: KAMY-HUAWEI-P30-BLE-GATEWAY06

text_sensor:
  - platform: wifi_info
    ip_address:
      name: ${friendly_name} IP Address
    ssid:
      name: ${friendly_name} Connected SSID
    bssid:
      name: ${friendly_name} Connected BSSID
    mac_address:
      name: ${friendly_name} MAC Wifi Address

button:
  - platform: restart
    name: ${friendly_name} Restart

sensor:
  - platform: startup
    name: ${friendly_name} Device Uptime
    id: ${devicename}_device_uptime
  - platform: wifi_signal
    name: ${friendly_name} Wifi Signal
    id: ${devicename}_wifi_signal
    update_interval: 60s
  - platform: template
    name: BETHAYN-ONEPLUS-8-BLE Distance
    id: bethayn_oneplus_8_ble_dist
    update_interval: 30s
    unit_of_measurement: m
    device_class: ""
    state_class: measurement
    accuracy_decimals: 1
    entity_category: diagnostic
    lambda: |-
      return getTracker("BETHAYN-ONEPLUS-8-BLE-GATEWAY06-1").get_dist();
  - platform: template
    name: KAMY-HUAWEI-P30-BLE Distance
    id: kamy_huawei_p30_ble_dist
    update_interval: 30s
    unit_of_measurement: m
    device_class: ""
    state_class: measurement
    accuracy_decimals: 1
    entity_category: diagnostic
    lambda: |-
      return getTracker("KAMY-HUAWEI-P30-BLE-GATEWAY06-1").get_dist();
```
I'm sure the 2 devices are transmitting because the ble_presence sensor detects them.
